FROM maven:3.9.8-eclipse-temurin-17
WORKDIR /app

ENV MAVEN_OPTS="-Dspring-boot.run.profiles=dev"

COPY pom.xml ./
RUN mvn dependency:go-offline -B

COPY src ./src

EXPOSE 8080

# Devtools ile hot reload
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false"]
